version: "1.0"
stages:
- "build"
- "push"
steps:
  clone:
    description: "Cloning main repository..."
    type: "git-clone"
    repo: "digitonic/cloudflare-cname"
    revision: "master"
    stage: "build"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "digitonic/website"
    tag: "master"
    dockerfile: "Dockerfile"
    stage: "build"
  push:
    type: push
    arguments:
      candidate: '${{build}}'
      tag: 'master'
      image_name: "digitonic1/website"
      registry: 'dockerhub'
    stage: "push"
    tags:
      - latest
    when:
      branch:
        only:
          - master