version: "1.0"
stages:
  - "build"
steps:
  main_clone:
    description: "Cloning main repository..."
    type: "git-clone"
    repo: "digitonic/cloudflare-cname"
    revision: "master"
    stage: "build"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "digitonic/cloudflare-cname"
    tag: "latest"
    stage: "build"
