version: "1.0"
stages:
- build
- push
steps:
  build_latest:
    type: build
    stage: build
    image_name: digitonic/cloudflare-cname
    tag: latest
  push_latest:
    type: push
    stage: push
    candidate: ${{build_latest}}
    registry: dockerhub
    tags:
    - latest
    - 0.1.0
    when:
      branch:
        only:
        - master
